// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7R5mRmYZKTTQI-dF2OtJOFTPUQTznC3c',
    appId: '1:18171976195:web:f4c702283cc237940ecc36',
    messagingSenderId: '18171976195',
    projectId: 'fir-auth-ece43',
    authDomain: 'fir-auth-ece43.firebaseapp.com',
    storageBucket: 'fir-auth-ece43.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-9iOEc6pevAIE3tNiLGBSvdCT0DUkKIM',
    appId: '1:18171976195:android:c87290feca6aeca40ecc36',
    messagingSenderId: '18171976195',
    projectId: 'fir-auth-ece43',
    storageBucket: 'fir-auth-ece43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3Ht8Co3A6yzMrJ0MuqcQYThRvOtHn8X8',
    appId: '1:18171976195:ios:2136e8e4c4168f5a0ecc36',
    messagingSenderId: '18171976195',
    projectId: 'fir-auth-ece43',
    storageBucket: 'fir-auth-ece43.appspot.com',
    iosClientId:
        '18171976195-evtor1kt9i9d8vq7hcpsjigjpeo78mg1.apps.googleusercontent.com',
    iosBundleId: 'com.example.delApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3Ht8Co3A6yzMrJ0MuqcQYThRvOtHn8X8',
    appId: '1:18171976195:ios:2136e8e4c4168f5a0ecc36',
    messagingSenderId: '18171976195',
    projectId: 'fir-auth-ece43',
    storageBucket: 'fir-auth-ece43.appspot.com',
    iosClientId:
        '18171976195-evtor1kt9i9d8vq7hcpsjigjpeo78mg1.apps.googleusercontent.com',
    iosBundleId: 'com.example.delApp',
  );
}
